env: dev  
restartPolicy: OnFailure
image:
  repository: XYZ
  tag: 1.0.2
  pullPolicy: IfNotPresent 
service: 
  internalPort: 8028  
crons:
 "0":
 name: cog-first-cron
 command: /opt/myapp/myscript1.sh
 schedule: "10 4 * * *"
 "1":
 name: cog-second-cron
 command: /opt/myapp/myscript2.sh
 schedule: "" 30 5 * * *" 
 "2":
 name: cog-third-cron
 command: /opt/myapp/myscript3.sh
 schedule: "0/5 * * * *" 