env: dev  
restartPolicy: OnFailure
image:
  repository: XYZ
  tag: 1.0.2
  pullPolicy: IfNotPresent 
service: 
  internalPort: 8028  
crons:
 "0":
 name: cog-first-cron
 command: /opt/myapp/myscript1.sh
 schedule: "*/10 * * * *"
 "1":
 name: cog-second-cron
 command: /opt/myapp/myscript2.sh
 schedule: « */3 * * * *" 